/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Marcin.Kwiatkowski (https://sketchfab.com/Marcin.Kwiatkowski)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vintage-cola-ae96cca627124596ad220a9814bf74f8
title: vintage Cola
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model_Cola_Bottle({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../../bottleCola.glb');
  const grp =
  <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
    <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
      <mesh geometry={nodes.bottlecola001_M_cola_0.geometry} material={materials.M_cola} />
    </group>
    <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
      <mesh geometry={nodes.capcola001_M_colacap_0.geometry} material={materials['M_cola.cap']} />
    </group>
    <group position={[0, 3.88, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[94.28, 94.28, 100]}>
      <mesh geometry={nodes.cola001_M_colatransparent_0.geometry} material={materials['M_cola.transparent']} />
    </group>
  </group>
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.51}>
        {grp}
      </group>
    </group>
  )
}

useGLTF.preload('../../../../bottleCola.glb')
